### ISSUE TITLE
can we make separate clients one for ios and one for android?

### ISSUE THREAD

**Issue by realkarim** [Ketabuk/Ketabuk-ionic2App#1]

**Comment by lordadamson** [comment]
Yes we definitely can. After a second thought about it I realized that ionic contributors will be scarce and it would be a better idea to go native.

**Comment by lordadamson** [comment]
Android: https://github.com/Ketabuk/Ketabuk-AndroidApp
iOS: https://github.com/Ketabuk/Ketabuk-IOSApp
